// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dispatch`, `install_crypto_provider`, `runtime`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SageClient>>
abstract class SageClient implements RustOpaqueInterface {
  /// Invoke any Sage endpoint by name with a JSON request body, returning
  /// the JSON response. Endpoint names and payloads are identical to
  /// Sage's RPC API (see the vendored `endpoints.json`).
  Future<String> call({required String endpoint, required String requestJson});

  /// Create and initialize a Sage wallet rooted at `data_dir`.
  ///
  /// This sets up the keychain, config, logging, peer sync manager and
  /// loads the active wallet (if a fingerprint was previously selected).
  /// `data_dir` should be an app-private, writable directory
  /// (e.g. `getApplicationSupportDirectory()` on Flutter).
  static Future<SageClient> newInstance({required String dataDir}) => RustLib
      .instance
      .api
      .crateApiSageClientSageClientNewInstance(dataDir: dataDir);
}
